### ISSUE TITLE
v7.6.9 is having issues Glitched empty WU unreturned. Client software freezes regularly.

### ISSUE THREAD

**Issue by automatedfleettechnician** [FoldingAtHome/fah-issues#1381] opened 2020-04-18 01:11 UTC
01:05:06:ERROR:WU01:FS01:Exception: Failed to advance statement result: The database file is locked
01:05:08:WU02:FS01:0x22:Completed 0 out of 2000000 steps (0%)
01:05:08:WU02:FS01:0x22:Temperature control disabled. Requirements: single Nvidia GPU, tmax must be < 110 and twait >= 900
01:05:16:ERROR:WU02:FS01:Exception: Failed to advance statement result: The database file is locked
01:05:17:ERROR:Receive error: 10053: 
An established connection was aborted by the software in your host machine.
01:05:38:WARNING:WU01:FS01:Exception: Failed to advance statement result: The database file is locked
01:05:38:WARNING:WU01:FS01:Detected clock skew (1 mins 02 secs), I/O delay, laptop hibernation or other slowdown noted, adjusting time estimates

Client now says it has 3 WUs downloaded. None of them completed but two are stuck at 0% SEND.
Advanced Control gets regularly stuck on the main page and only reads "Client: local Updating Inactive

F@H software has worked perfectly for the past month but this release is so buggy I'm going to have to uninstall it until something is figured out.

01:12:33:WARNING:WU01:FS01:Detected clock skew (1 mins 02 secs), I/O delay, laptop hibernation or other slowdown noted, adjusting time estimates

These warnings keep popping up every few minutes in the log now.

This same machine has performed flawlessly for the past month. The only software change has been the F@H client update.

Computer is an Asus laptop with an AMD CPU/GPU but it also has an Nvidia RTX mobile edition. I had configured the client to use the RTX at full power 24/7 while I did basic file editing, programming, Word 365, Visual Studio Code and such with the rest of the system. 
Currently running Windows 10 64-bit Home edition, 16Gb Ram, 6Gb Video Memory, SSD storage.

**Comment by PantherX** [comment] 2020-04-18 02:38
Can you please post your log file in the Official Forum: https://foldingforum.org/index.php

We can troubleshoot there since 7.6.9 is a stable release and we haven't identified what the issue is. Once the issue is identified on the Forum, an issue will be raised here. Based on this, I will close this issue.

**Closed by PantherX** 2020-04-18 02:38 UTC

**Comment by automatedfleettechnician** [comment] 2020-04-18 02:45
"Stable"
