### ISSUE TITLE
When a WU is enqueued for upload FAHControl always shows SEND 100%

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1184] opened 2017-03-01 22:22 UTC
During the time that a result is uploading, the Progress indicator should show the actual progress.

The log shows the numbers, but they're not reflected in the GUI.
22:13:36:WU01:FS00:Upload 68.66%
22:13:42:WU01:FS00:Upload 71.46%
22:13:48:WU01:FS00:Upload 73.13%
22:14:02:WU01:FS00:Upload 75.92%
22:14:08:WU01:FS00:Upload 77.04%
22:14:14:WU01:FS00:Upload 79.27%
22:14:20:WU01:FS00:Upload 81.50%
22:14:26:WU01:FS00:Upload 84.29%
22:14:32:WU01:FS00:Upload 86.53%
22:14:39:WU01:FS00:Upload 89.32%
22:14:45:WU01:FS00:Upload 91.55%
22:14:52:WU01:FS00:Upload 94.34%
22:14:59:WU01:FS00:Upload 97.13%
22:15:05:WU01:FS00:Upload 99.93%
22:15:11:WU01:FS00:Upload complete

**Comment by jcoffland** [comment] 2017-03-03 05:23
This is a duplicate of #644.

**Closed by jcoffland** 2017-03-03 05:23 UTC
