### ISSUE TITLE
FAHClient ignores IPV6 on LAN 

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1205] opened 2017-07-05 21:06 UTC
When connecting to other (local) clients using the left column of FAHControl, I generally like to use the client hostname rather than the IPV4 address.  (This is one way to resolve DHCP changes.)

In Windows (and maybe elsewhere) the hostname resolves to both an IPV6 and an IPV4 address.  Newer versions of Windows default to "Prefer IPV6" and the remote host fails to connect.

I have found a patch on the  Microsoft site to change my registry to "Prefer IPV4" and that does work. 

Inasmuch as #505 seems a rather remote possibility, does anybody have a better solution? 

[It should be noted that when a remote client fails to connect, it's a rather arduous process to figure out which of the multitude of possibilities is blocking the connection.]

**Comment by jcoffland** [comment] 2017-10-30 19:34
The client does not support IPv6.  This is a duplicate of #505.

**Closed by jcoffland** 2017-10-30 19:34 UTC
Labels: duplicate, enhancement, FAHClient
