### ISSUE TITLE
Cannot install fahcontrol in Linux Mint 20

### ISSUE THREAD

**Issue by holmesrichards** [FoldingAtHome/fah-issues#1539] opened 2020-07-09 20:35 UTC
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **fahcontrol_7.6.13-1**
* **Linux Mint 20**

----
## Expected Behavior

Should have been able to install

----
## Current Behavior

Could not install

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1. Download fahcontrol_7.6.13-1_all.deb
2. Double click on icon 
3. Window has error message: "Error: Dependency is not satisfiable: python"

----
## Context

----

**Comment by ChristianVirtual** [comment] 2020-07-09 21:37
Have you seen this posting in the support forum ?
https://foldingforum.org/viewtopic.php?f=108&t=35707

**Comment by ffissore** [comment] 2020-07-10 08:12
Duplicate of #858

**Closed by ffissore** 2020-07-10 08:12 UTC
