### ISSUE TITLE
Throttling Retry Attempts after PLEASE_WAIT Server Response

### ISSUE THREAD

**Issue by uyaem** [FoldingAtHome/fah-issues#1371] opened 2020-04-15 05:22 UTC
There have been numerous threads on the forums about uploads timing out, and clients receiving the PLEASE_WAIT server response, e.g. https://foldingforum.org/viewtopic.php?f=18&t=34116&start=45#p325635 (and rest of thread).

Similar to WU assignment requests, there seems to be an exponential back-off strategy in place, that starts with a very small time span.  Essentially, clients immediately start uploading again to the same server.
Since the PLEASE_WAITs often seem to be due to "server under too much load" or "disk full", I feel that the behaviour is contributing to the problem and should maybe looked at at the same time as the back-off strategy for WU assignments, i.e.:
- longer time until the first retry
- timespan between retries either constant, or increasing linerarly

**Comment by shorttack** [comment] 2020-04-15 20:22
@uyaem We are aware we have to do a better job at the backend and in the client. I am closing this because it is front and center to Development due to the explosive growth of the project, and a duplicate of other issues.

**Closed by shorttack** 2020-04-15 20:22 UTC
Labels: duplicate, enhancement
