### ISSUE TITLE
F@H stopped folding, Donno why...

### ISSUE THREAD

**Issue by TheUnjust117** [FoldingAtHome/fah-issues#1469] opened 2020-05-08 03:45 UTC
done eveyrthing to uninstall and reinstall...

![image](https://user-images.githubusercontent.com/65001926/81367903-54ee4280-90e6-11ea-8f44-de74d119a8d8.png)
 sticks here...
log file to follow...

[log.txt](https://github.com/FoldingAtHome/fah-issues/files/4596886/log.txt)

help plz?

**Comment by PantherX** [comment] 2020-05-08 08:07
Please note that we prefer to use GitHub to document known issues and how to reproduce them. For general troubleshooting, please hop over to the Official Forum where there are lots of Donors who would be happy to help you out: https://foldingforum.org/index.php

Since this is not an issue, I will close this now :)

**Closed by PantherX** 2020-05-08 08:07 UTC
