### ISSUE TITLE
Windows 10 64 + Geforce 1060. FAH 7.6.9 can't detect Geforce 1060, but FAH 7.5.1 can

### ISSUE THREAD

**Issue by komil-tymchenko** [FoldingAtHome/fah-issues#1388] opened 2020-04-18 13:50 UTC
FAH 7.6.9 can't detect Geforce 1060, but FAH 7.5.1 can.
I Uninstalled 7.5.1 with deleting data checkbox.
After few weeks I installed  7.6.9  and GPU was not detected

**Comment by komil-tymchenko** [comment] 2020-04-18 13:52
![f1](https://user-images.githubusercontent.com/30898406/79639514-fd1e8480-8194-11ea-8a3e-47ac9d9b10d7.png)
![f2](https://user-images.githubusercontent.com/30898406/79639515-fdb71b00-8194-11ea-83ce-ef8b9c709fcf.png)
![f12](https://user-images.githubusercontent.com/30898406/79639516-fdb71b00-8194-11ea-8c8a-000e1a4c2d52.png)
![f21](https://user-images.githubusercontent.com/30898406/79639517-fe4fb180-8194-11ea-8f05-fe93f45441f0.png)

**Comment by shorttack** [comment] 2020-04-18 16:30
@komil-tymchenko 
Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed?

Please note that since we haven't investigated what the underlying issue is, I am going to close this ticket. Once the issue is identified and reproducible, an issue will be raised here. GitHub is not used for troubleshooting, the Forum is :)

_Issue Support_

**Comment by komil-tymchenko** [comment] 2020-04-18 16:49
@shorttack  guys from official forum told me to report it here
https://foldingforum.org/viewtopic.php?f=101&t=34491&e=0#p327194

**Comment by shorttack** [comment] 2020-04-18 18:51
Source: [https://foldingforum.org/viewtopic.php?f=101&t=34491&e=0#p327194](url)

**Comment by shorttack** [comment] 2020-04-18 19:10
@komil-tymchenko Please try release 7.6.10, which fixes a problem on a clean install of not finding GPUs. [https://foldingathome.org/beta/](url)

Close: fixed 7.6.10

**Comment by komil-tymchenko** [comment] 2020-04-19 06:26
Thanks, in new build It works fine!

**Closed** 2020-04-22 09:09 UTC
Labels: FAHControl, Windows, fixed
