### ISSUE TITLE
Update Reminder

### ISSUE THREAD

**Issue by G-A-Waringer** [FoldingAtHome/fah-issues#1519] opened 2020-06-08 04:26 UTC
As a not so frequently web site visitor, I'd much appreciate some update reminder in the FAH client.

Would need 
- some version code (probably a single integer number would do) stored on an existing web server
- some code in the clent that requests that code, checks it against it's own code
- a message box that states "A new version of the client is available" if applicable

**Comment by PantherX** [comment] 2020-06-08 04:47
Hiya @G-A-Waringer 
Please note that I consider this to be a duplicate of this existing issue (https://github.com/FoldingAtHome/fah-issues/issues/1404). If that isn't the case, please state what the difference is :)

**Closed by PantherX** 2020-06-08 04:47 UTC
