### ISSUE TITLE
FAHViewer (on Windows, at least) V7.5.1 always displays the Demo protein. 

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1283] opened 2019-05-30 22:25 UTC

**Comment by bb30994** [comment] 2019-05-30 22:30
1) I am unable to display any active protein, no matter which FAHCore is running.  This is true whether FAHViewer is launched from FAHControl or as a stand-alone program.

2) I Can find no documentation for invoking the stand-alone FAHViewer.

3) FAHviewer 7.4.4 can show GPU work units being generated by Core_22 and perhaps some other FAHCores.

**Comment by bb30994** [comment] 2019-06-17 15:35
> I can't get FAHViewer to work so I took a network trace on 127.0.0.1 and saw FAHV connect to the FAHClient ok, but FAHV immediately disconnected without waiting for any response from the client:
> 
> In English:
> 
> 1. Viewer connects to FAHClient ok
> 2. Viewer disconnects from Client about 1/6000th of a second later
> 3. An in-flight message "Welcome to the Folding@home Client command server" is received from FAHClient
> 4. That's All Folks.
> 
> In technobabble network trace speak:
> 
> This is FAHV connecting...
> 13:41:18.085393 49780 → 36330 [SYN] Seq=0 Win=64240 Len=0 MSS=65495 WS=256 SACK_PERM=1
> This is FAHC acknowledging the connection...
> 13:41:18.085424 36330 → 49780 [SYN, ACK] Seq=0 Ack=1 Win=65535 Len=0 MSS=65495 WS=256 SACK_PERM=1
> 13:41:18.085551 49780 → 36330 [ACK] Seq=1 Ack=1 Win=525568 Len=0
> 
> This is FAHV disconnecting...
> 13:41:18.085723 49780 → 36330 [FIN, ACK] Seq=1 Ack=1 Win=525568 Len=0
> 13:41:18.085737 36330 → 49780 [ACK] Seq=1 Ack=2 Win=525568 Len=0
> 
> FAHV didn't even wait for the welcome response...
> 13:41:18.188657 36330 → 49780 [PSH, ACK] Seq=1 Ack=2 Win=525568 Len=60 "Welcome to the Folding@home Client command server"
> 13:41:18.188869 49780 → 36330 [RST, ACK] Seq=2 Ack=61 Win=0 Len=0 RST=Connection Reset aka winsock error 10053
> 
> 2 guesses:
> 
> 1. The receive timeout is wrong
> 2. It's a non-blocking socket being read when no data is available to read. On Windows recv() will return SOCKET_ERROR (-1) to flag a status code. You need to call WSAGetLastError() to get the status code - if it returns WSAEWOULDBLOCK (10035) then it just means no data to read yet and try again later. -1 from recv() is not always a fatal error. On Linux check errno for EWOULDBLOCK or EAGAIN (I just googled Linux - I'm not a know-it-all).
> 
> I just found the source code (Client.cpp):
> 
> setBlocking(false);
> 
> So it is a non-blocking socket.
> 
> Code: Select all
>     int count = read();
> 
>     if (count <= 0) {
>           if (count < 0 || lastData + 20 < Time::now()) reconnect();
>           return false;
>     }
> 
> 
> 
> The above could potentially fail forever if the client has a tiny delay in sending something immediately after connection, and the viewer is too impatient to wait just a tiny bit for it's first read() to succeed.
> 
> Windows 10 64-bit Intel i7 6700k.

**Comment by jcoffland** [comment] 2019-06-17 21:45
But the code that implements ``Socket::read()`` does handle those return codes correctly.  See https://github.com/CauldronDevelopmentLLC/cbang/blob/master/src/cbang/socket/SocketDefaultImpl.cpp#L343

Although, since the viewer is disconnecting immediately, the problem must be somewhere in this vicinity.

**Comment by NuovaApe** [comment] 2019-06-21 22:17
> But the code that implements `Socket::read()` does handle those return codes correctly. See https://github.com/CauldronDevelopmentLLC/cbang/blob/master/src/cbang/socket/SocketDefaultImpl.cpp#L343
> 
> Although, since the viewer is disconnecting immediately, the problem must be somewhere in this vicinity.

I was the OP of that trace on https://foldingforum.org/viewtopic.php?f=16&t=31663
Unaware cbang on here - should have checked.

checkConnect() will fail the socket writeability test if called before the TCP handshake has completed. 

MS doc

"The parameter writefds identifies the sockets that are to be checked for writability. If a socket is processing a connect call (nonblocking), a socket is writeable if the connection establishment successfully completes".
(https://docs.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-select)

Maybe it hasn't completed...yet?

You can connect() in blocking mode. When it returns you can then switch to non-blocking. Then the writeability status confirms connected/failed, excluding "pending".

https://stackoverflow.com/questions/20597240/setting-a-socket-nonblocking-after-a-blocking-connect

Debugging in my head. Hopefully I've been more thorough this time.

**Comment by jcoffland** [comment] 2019-06-21 22:33
``checkConnect()`` is a likely candidate but I'm still not seeing the problem.

```c++
void Client::checkConnect() {
  try {
    SocketSet socketSet;
    socketSet.add(*this, SocketSet::WRITE | SocketSet::EXCEPT);
    socketSet.select(0);

    if (!socketSet.isSet(*this, SocketSet::EXCEPT)) {
      if (socketSet.isSet(*this, SocketSet::WRITE)) {
        lastData = Time::now();
        sendCommands(command);
        state = STATE_HEADER;
      }

      return;
    }
  } CLIENT_CATCH_ERROR;

  // Some error occured
  reconnect();
}
```

So ``reconnect()`` gets called if there was a socket exception or if an exception was thrown.  If an exception was thrown, it would be caught and logged by ``CLIENT_CATCH_ERROR``.

The MSDN document you linked above says that there should only be a socket exception:

 * If processing a connect call (nonblocking), connection attempt failed.
 * OOB data is available for reading (only if SO_OOBINLINE is disabled).

There should not be any out-of-band data so the socket exception should only occur when the connection failed.

**Comment by NuovaApe** [comment] 2019-06-22 01:09
You are more awake than I - I concur.

This line, maybe?

`socketSet.select(0);`

"If TIMEVAL is initialized to {0, 0}, select will return immediately"
"the standard assumptions for nonblocking calls apply. For example, the blocking hook will not be called, and Windows Sockets will not yield."

I have no idea what the standard assumptions are or what that implies. Scraping the bottom of the barrel I found a 16-bit Windows quote:

> 5. Polling with select() and a zero timeout in Win16’s non-preemptive environment. Nauseatingly lame.
> 
> Reason: With any non-zero timeout, select() will call the current blocking hook function, so an application anticipating an event will yield to other processes executing in a 16-bit Windows environment. However, with a zero timeout an application will not yield to other processes, and may not even allow network operations to occur (so it will loop forever).
> Alternative: Use a small non-zero timeout
> 
(https://tangentsoft.net/wskfaq/articles/lame-list.html)

Studying checkConnect once more, if never EXCEPT or WRITE it remains in STATE_CONNECTING for ever.

Could Windows legacy logic, using a select(0) timeout, cause it?

**Comment by jcoffland** [comment] 2019-06-27 02:27
Not sure.  I'm focusing on a new F@H client so this will be obsolete in the near future.

**Comment by Sandman192** [comment] 2020-02-14 22:54
Just to note, I a get this error every 15 sec and only if I have the F@H Viewer running.

19:52:21:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.

**Comment by murkey** [comment] 2020-03-09 20:17
+1, same problem, same error
```
20:13:11:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
20:13:27:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
20:13:43:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
```

**Comment by bb30994** [comment] 2020-03-12 23:06
I get this same message, though certainly not every 15 seconds ... and I don't run the Viewer.  At the very least the message should indicate where it's coming from   (What connection was aborted?)

Mine might be from HFM.  I've noticed some missing data in HFM recently but have diagnosed the problem yet.

**Comment by informatorius** [comment] 2020-03-14 21:17
A workaround for the demo protein problem on V7.5.1 is to use the V7.4.4 FAHViewer.exe which shows FahCore_22 GPU work units.

**Comment by carlomontec** [comment] 2020-03-15 15:35
Where can I download previous versions? The downloads section seems to be down. 
Thank you.

**Comment by informatorius** [comment] 2020-03-15 15:55
https://www.reddit.com/r/Folding/comments/fgxa4w/2_issues/fkk4w8o/?context=3

**Comment by str4d** [comment] 2020-03-21 10:28
I compiled current master of https://github.com/FoldingAtHome/fah-viewer (Windows 10, Visual C++ 2019) and the resulting `FAHViewer.exe` was able to connect to FAH 7.5.1 and display the current protein. I think that means this was fixed in https://github.com/FoldingAtHome/fah-viewer/commit/8d9062530dcdba101eb768f1af1cb90f232d7f0f, and we just need a new release.

**Comment by str4d** [comment] 2020-03-21 10:34
FAHScreensaver in 7.5.1 is also unable to connect to FAH and falls back to displaying the Demo protein. As it wraps FAHViewer, I suspect that the above fix will also fix the screensaver, but I'll try compiling it locally to check.

**Comment by sopex** [comment] 2020-03-21 21:49
@str4d Could you provide the executable.

**Comment by str4d** [comment] 2020-03-21 22:11
Built from https://github.com/FoldingAtHome/fah-viewer/commit/091713f412678b1a57091ae3490dd3fc4ef65e6e using Windows 10 and VC++ 2019. Includes `freetype.dll` from https://github.com/ubawurinna/freetype-windows-binaries/tree/e4504fd25d7d23797ccfef336a33491c0d654129/win64.

[FAHViewer-091713f412-windows-x86_64.zip](https://github.com/FoldingAtHome/fah-issues/files/4364298/FAHViewer-091713f412-windows-x86_64.zip)

**Comment by stratege1401** [comment] 2020-03-21 22:46
> Built from [FoldingAtHome/fah-viewer@091713f](https://github.com/FoldingAtHome/fah-viewer/commit/091713f412678b1a57091ae3490dd3fc4ef65e6e) using Windows 10 and VC++ 2019. Includes `freetype.dll` from https://github.com/ubawurinna/freetype-windows-binaries/tree/e4504fd25d7d23797ccfef336a33491c0d654129/win64.
> 
> [FAHViewer-091713f412-windows-x86_64.zip](https://github.com/FoldingAtHome/fah-issues/files/4364298/FAHViewer-091713f412-windows-x86_64.zip)

Hello.

just test it, here is a screen capt. Working just fine.
<img width="761" alt="foldingfix" src="https://user-images.githubusercontent.com/8655165/77238140-21a33300-6bce-11ea-9377-e334bd598675.png">

**Comment by jcoffland** [comment] 2020-03-22 00:14
> I think that means this was fixed in [FoldingAtHome/fah-viewer@8d90625](https://github.com/FoldingAtHome/fah-viewer/commit/8d9062530dcdba101eb768f1af1cb90f232d7f0f), and we just need a new release.

I believe that is true.

**Comment by sopex** [comment] 2020-03-22 08:48
> I compiled current master of https://github.com/FoldingAtHome/fah-viewer (Windows 10, Visual C++ 2019) and the resulting `FAHViewer.exe` was able to connect to FAH 7.5.1 and display the current protein. I think that means this was fixed in [FoldingAtHome/fah-viewer@8d90625](https://github.com/FoldingAtHome/fah-viewer/commit/8d9062530dcdba101eb768f1af1cb90f232d7f0f), and we just need a new release.

I can confirm that it worked for me too.

**Comment by MeertenR** [comment] 2020-03-23 22:27
Is this actually the protein being folded? Looks like random values to me.
Also viewing 0x22 crashes the viewer 50% of the time on my system. I wouldn't call it "working" yet.
![image](https://user-images.githubusercontent.com/62556936/77368889-880a8b80-6d5d-11ea-9a8b-91c02baa978c.png)

**Comment by modem7** [comment] 2020-03-23 23:27
> 
> 
> Is this actually the protein being folded? Looks like random values to me.
> Also viewing 0x22 crashes the viewer 50% of the time on my system. I wouldn't call it "working" yet.
> ![image](https://user-images.githubusercontent.com/62556936/77368889-880a8b80-6d5d-11ea-9a8b-91c02baa978c.png)

Aye, I'm getting the same here

![image](https://user-images.githubusercontent.com/4349962/77372564-cb64fa00-6d5d-11ea-8e29-448441f2bfc1.png)

**Comment by str4d** [comment] 2020-03-24 01:00
That looks like a different issue; you're still receiving data from FAHClient, whereas this issue is about FAHViewer not connecting to FAHClient at all.

**Comment by jort93** [comment] 2020-03-24 01:16
I just wanna say that I had the same issue, went through some troubleshooting and this is what fixed it for me as well.
Just an issue with the release it seems.

**Comment by MeertenR** [comment] 2020-03-24 07:31
> That looks like a different issue; you're still receiving data from FAHClient, whereas this issue is about FAHViewer not connecting to FAHClient at all.

Reason I'm mentioning this here is because at some point I was wondering if the person responsible for release may have intentionally (temporarily) put it into Demo mode as to prevent these crashes and this completely unrepresentative protein from being displayed. Until 0x22 sim is fixed.

One could argue that showing the Demo protein is the lesser of evils.

**Comment by waterspeier** [comment] 2020-03-24 17:29
> Built from [FoldingAtHome/fah-viewer@091713f](https://github.com/FoldingAtHome/fah-viewer/commit/091713f412678b1a57091ae3490dd3fc4ef65e6e) using Windows 10 and VC++ 2019. Includes `freetype.dll` from https://github.com/ubawurinna/freetype-windows-binaries/tree/e4504fd25d7d23797ccfef336a33491c0d654129/win64.
> 
> [FAHViewer-091713f412-windows-x86_64.zip](https://github.com/FoldingAtHome/fah-issues/files/4364298/FAHViewer-091713f412-windows-x86_64.zip)

Works for me, too.
Thanks for that.

**Comment by djtuBIG-MaliceX** [comment] 2020-03-25 01:58
Confirmed fix is working, now connecting and got visual on protein viewer.
![image](https://user-images.githubusercontent.com/3403183/77493823-403c4f00-6e98-11ea-9314-00a7d38e8c3c.png)

**Comment by suntzu420** [comment] 2020-03-25 05:35
> Built from [FoldingAtHome/fah-viewer@091713f](https://github.com/FoldingAtHome/fah-viewer/commit/091713f412678b1a57091ae3490dd3fc4ef65e6e) using Windows 10 and VC++ 2019. Includes `freetype.dll` from https://github.com/ubawurinna/freetype-windows-binaries/tree/e4504fd25d7d23797ccfef336a33491c0d654129/win64.
> 
> [FAHViewer-091713f412-windows-x86_64.zip](https://github.com/FoldingAtHome/fah-issues/files/4364298/FAHViewer-091713f412-windows-x86_64.zip)

Can confirm this worked for me as well. 
![image](https://user-images.githubusercontent.com/11185585/77505164-6af2bd00-6e30-11ea-9de0-a3a53fc4d943.png)

**Comment by Hou5e** [comment] 2020-03-25 13:31
Outside the scope of this initial issue, this conversation is taking about the purple atoms probably not being sized and colored correctly?? https://foldingforum.org/viewtopic.php?f=106&t=32628&p=318105#p317593

**Comment by ValZapod** [comment] 2020-03-26 22:09
> That looks like a different issue; you're still receiving data from FAHClient, whereas this issue is about FAHViewer not connecting to FAHClient at all.

But, is not it the same (pink water) if you use 7.4.4 as described here? https://gist.github.com/alfanhui/fd69de8354047609fad5ebbef829eb94

**Comment by informatorius** [comment] 2020-03-27 22:18
Does the pink water go away when you switch to alternative representation modes? Press "h" key to see all other keys and options. Keys 1-9 switch representation modes.

**Comment by MithrasPan** [comment] 2020-03-29 02:50
While not strictly relevant to the OP... in my case, using the above compiled and linked FAHviewer.exe lets the Viewer connect but introduces the 'pink water'. Changing representation modes does not eliminate the pink in my case but I feel this issue should probably be moved to a new issue as I feel its more related to the warning that the updated Viewer if for CPU WUs only.

I have my client paused for a bit and haven't properly tested but I think the pink water only shows up on GPU WUs? Anybody know of an existing issue that could be linked?

**Comment by andylh66** [comment] 2020-03-30 15:35
> Built from [FoldingAtHome/fah-viewer@091713f](https://github.com/FoldingAtHome/fah-viewer/commit/091713f412678b1a57091ae3490dd3fc4ef65e6e) using Windows 10 and VC++ 2019. Includes `freetype.dll` from https://github.com/ubawurinna/freetype-windows-binaries/tree/e4504fd25d7d23797ccfef336a33491c0d654129/win64.
> 
> [FAHViewer-091713f412-windows-x86_64.zip](https://github.com/FoldingAtHome/fah-issues/files/4364298/FAHViewer-091713f412-windows-x86_64.zip)

thanks  @str4d this works for me too

**Comment by sthaber** [comment] 2020-04-01 06:56
> While not strictly relevant to the OP... in my case, using the above compiled and linked FAHviewer.exe lets the Viewer connect but introduces the 'pink water'. Changing representation modes does not eliminate the pink in my case but I feel this issue should probably be moved to a new issue as I feel its more related to the warning that the updated Viewer if for CPU WUs only.
> 
> I have my client paused for a bit and haven't properly tested but I think the pink water only shows up on GPU WUs? Anybody know of an existing issue that could be linked?

This looks like the same issue: https://github.com/FoldingAtHome/fah-issues/issues/1341

**Comment by sthaber** [comment] 2020-04-01 06:57
> I compiled current master of https://github.com/FoldingAtHome/fah-viewer (Windows 10, Visual C++ 2019) and the resulting `FAHViewer.exe` was able to connect to FAH 7.5.1 and display the current protein. I think that means this was fixed in [FoldingAtHome/fah-viewer@8d90625](https://github.com/FoldingAtHome/fah-viewer/commit/8d9062530dcdba101eb768f1af1cb90f232d7f0f), and we just need a new release.

Thanks for the build! It seems like there hasn't been a release for... two years? Is that right? Do they ever pick up and release changes from github?

**Comment by hallipr** [comment] 2020-04-07 18:39
It looks like release 7.5.1 was built 2 years ago:
https://download.foldingathome.org/releases/public/release/fahviewer/
```
windows-10-32bit/                                  31-May-2018 19:22                   -
windows-2008-64bit/                                03-May-2018 20:32                   -
windows-xp-32bit/                                  03-May-2018 20:32                   -
```

Does anyone have a fork with a published release for win-10?

**Comment by shorttack** [comment] 2020-04-14 01:12
Closed: 7.6.x version support

**Closed by shorttack** 2020-04-14 01:12 UTC
Labels: FAHViewer

**Comment by ratticon** [comment] 2020-04-14 16:35
> Built from [FoldingAtHome/fah-viewer@091713f](https://github.com/FoldingAtHome/fah-viewer/commit/091713f412678b1a57091ae3490dd3fc4ef65e6e) using Windows 10 and VC++ 2019. Includes `freetype.dll` from https://github.com/ubawurinna/freetype-windows-binaries/tree/e4504fd25d7d23797ccfef336a33491c0d654129/win64.
> 
> [FAHViewer-091713f412-windows-x86_64.zip](https://github.com/FoldingAtHome/fah-issues/files/4364298/FAHViewer-091713f412-windows-x86_64.zip)

Works fine for me! Awesome! Thanks!

Spec:
Windows 10 64-bit
Intel i7-7700K @ 4.20Ghz
Nvidia GTX 1080

**Comment by hallipr** [comment] 2020-04-14 18:49
What does the message 

> Closed: 7.6.x version support

What does this mean?

**Comment by shorttack** [comment] 2020-04-14 18:54
> What does this mean?
The case is closed. It is fixed in 7.6. there is nothing (more) for the development team to do. You can try it at [https://foldingathome.org/beta/](url)

Yes, the 7.5 client, control, and viewer are 2 years old.

**Comment by ValZapod** [comment] 2020-04-14 18:58
@shorttack Put it to stable please (the viewer only maybe). That is not cool.

**Comment by shorttack** [comment] 2020-04-14 19:08
> Put it to stable please (the viewer only maybe)
The beta with the fix to viewer is at https://foldingathome.org/beta/ It will be released to stable when the beta is over.

**Comment by ValZapod** [comment] 2020-04-14 19:09
This is breaking error. You can cherry pick the changes up to the git bisected fix commit only for the viewer and not for the client and release it to stable.

**Comment by ex-nerd** [comment] 2020-04-14 19:53
@shorttack Hard to verify that this is fixed in the beta because I can't get the beta to run _at all_.  ... and this is after moving the FAHClient folder to the desktop (because it has "in use files" the uninstaller can't touch), rebooting, manually deleting the FAHClient folder, installing the beta (but NOT starting it), uninstalling the beta (to delete my data directory, just in case), reinstalling the beta...  Trying to open FAHClient or FAHControl from the beta does "nothing" (though something is seemingly running because that whole "in use files" issue mentioned above)

**Comment by Gadmek** [comment] 2020-04-15 03:50
the recompiled exe runs fine for me as well on one of the covid projects (13862)

9900K
2070 RTX Super
32Gb ram
Win 10

![Capture](https://user-images.githubusercontent.com/5280447/79296744-e7157900-7ea1-11ea-9046-f95d7d2d067d.PNG)

**Comment by j0taDasFestas** [comment] 2020-04-15 23:27
> Built from [FoldingAtHome/fah-viewer@091713f](https://github.com/FoldingAtHome/fah-viewer/commit/091713f412678b1a57091ae3490dd3fc4ef65e6e) using Windows 10 and VC++ 2019. Includes `freetype.dll` from https://github.com/ubawurinna/freetype-windows-binaries/tree/e4504fd25d7d23797ccfef336a33491c0d654129/win64.
> 
> [FAHViewer-091713f412-windows-x86_64.zip](https://github.com/FoldingAtHome/fah-issues/files/4364298/FAHViewer-091713f412-windows-x86_64.zip)

Working now thanks very much !

**Comment by waded** [comment] 2020-04-16 16:34
I can confirm viewer in the 7.6.8 Windows install package from https://foldingathome.org/beta/ now connects and shows the work unit. I no longer have to use 7.4.4 as a workaround. Thanks for getting the fix into a binary release!

**Comment by j0taDasFestas** [comment] 2020-04-17 13:34
> I can confirm viewer in the 7.6.8 Windows install package from https://foldingathome.org/beta/ now connects and shows work unit(s). I no longer have to use 7.4.4 as a workaround. Thanks for getting the fix into a binary release!

I tryed it but my gpu isn't showing in beta version. Ill revert to stable with the fix provided up by andylh66
