### ISSUE TITLE
EVGA RTX 2060 KO Ultra

### ISSUE THREAD

**Issue by pantherarmsar10** [FoldingAtHome/fah-issues#1453] opened 2020-05-03 03:59 UTC
I cannot seem to get F@H to reconize my GPU

**Comment by PantherX** [comment] 2020-05-03 04:13
Hi,
Please note that the V7.6.9 requires a system reboot for the GPU to be identified. This has been fixed in the latest beta. If you require additional help, please head over to the Official Forum: https://foldingforum.org/index.php

We prefer to use GitHub for documented issues which are reproducible for the developers to fix. Anything else, the Forum is for. Since this isn't an issue, I will be closing this now :)

**Closed by PantherX** 2020-05-03 04:13 UTC
