### ISSUE TITLE
FAHViewer 7.6.9 missing GLIBC_2.25 on Ubuntu 16.04

### ISSUE THREAD

**Issue by alextoind** [FoldingAtHome/fah-issues#1454] opened 2020-05-03 09:16 UTC
When I launch FAHViewer from a terminal it prompts out:
```
FAHViewer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by FAHViewer)
```
What should I check to solve this issue?

As from the title, I still use an old Ubuntu 16.04...

**Comment by shorttack** [comment] 2020-05-06 15:23
@alex Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed? Once the issue is identified and reproducible, an issue will be raised here. GitHub is not used for troubleshooting, the Forum is. 

We still support Ubunti 16 (but not 14). You can always try the latest beta at [www.foldingathome.org/beta](url) 
-IssueSupport-

**Comment by informatorius** [comment] 2020-05-07 06:18
Looks like this is some error with python 3?
https://stackoverflow.com/questions/59105412/python-in-ubuntu-16-04-lts-gives-error-lib-x86-64-linux-gnu-libc-so-6-version

**Comment by PantherX** [comment] 2020-06-07 04:35
Please note that I will close this issue now as it it has been deferred to Support.

**Closed by PantherX** 2020-06-07 04:35 UTC
Labels: 0.Status - Deferred To Support, 3.Component - FAHViewer, 4.OS - Debian
