### ISSUE TITLE
JSON API broken

### ISSUE THREAD

**Issue by bls1999** [FoldingAtHome/fah-issues#1235] opened 2018-06-04 02:53 UTC
The JSON API for stats lookup is broken. All it does is redirect to the search GUI. Click any of the links on [this page](https://stats.foldingathome.org/api) to see what I'm talking about.

**Comment by sombraguerrero** [comment] 2018-06-04 04:17
I posted about this on the forums too. It's not *technically* totally broken. The problem is that the JSON data is getting retrieved in a separate GET call that's happening AFTER the stats page loads, so something probably happened when they transitioned to https://stats.foldingathome.org.

**Comment by jcoffland** [comment] 2018-06-04 17:09
It's fixed now.  The problem was in the documentation.  The examples were pointing to the wrong place.

**Closed by jcoffland** 2018-06-04 17:09 UTC
