### ISSUE TITLE
Fahcore has failed

### ISSUE THREAD

**Issue by mattreecebentley** [FoldingAtHome/fah-issues#1515] opened 2020-06-04 00:45 UTC
OS: win7 x64 sp1, win10 1909 x64
Folding ver: 7.6.13

Folding is giving the following message on several machines:
fahcore_a7.exe has stopped working.

There doesn't seem to be any rhyme or reason to it. But I'm sick of it.

It also occurred with earlier versions.
It most often occurs on startup.

**Comment by mawelo** [comment] 2020-06-04 05:57
Well nothing is perfect. No you and not any kind of software. But we all need the data to fight against corona & co. 
Could you please so kind to post the complete log file ? Please let me try to help.

**Comment by PantherX** [comment] 2020-06-04 07:52
Hiya @mattreecebentley 
Sorry to hear about the issues. I would suggest that you hop over to the Official Forum (https://foldingforum.org/index.php) where there are several members happy to troubleshoot your issues.

Hiya @mawelo 
Appreciate your help and hopefully, you can join the Forum too :)

Please note that since this isn't an issue, I will be closing it. We tend to use GitHub for confirmed issues for the development team to resolve.

P.S. In future, please use the template as it makes triaging the issues by the volunteers a lot easier. In future, issues not using the template might not be considered.

**Closed by PantherX** 2020-06-04 07:52 UTC

**Comment by mattreecebentley** [comment] 2020-06-04 10:26
Is this a joke?
First a volunteer complains about 'nothing is perfect', which is far from a helpful attitude.
Then you close the issue without a valid cause.
I followed the template, but there was nothing further to add.
Please don't supply a link to your github page if you plan to execute with so little authority and attitude.

**Comment by PantherX** [comment] 2020-06-05 07:50
@mattreecebentley 
Apologies if this appears as a joke to you... it isn't and wasn't my intention at all. I can't speak about @mawelo's action but I assume they had good intention at heart.

Sorry if my message was a bit terse... when I said that this isn't an issue, I meant that it isn't a fully documented and reproducible issue. However, if you head over to the Forums where you can troubleshoot you issue, we can either resolve the issue on your system or come up with a precise set of steps which can be converted into a GitHub issue that has all the information required for the development team.

There are several Donors who are running Windows 10 and some are running Windows 7 that are folding without issues. If we can identify what's unique about your system and confirm if that is indeed a bug, that would help out others in the same boat.

The GitHub link was a replacement to a dead link when the website migrated. I wasn't aware of that and another member notified me of that so I have created an enhancement request (https://github.com/FoldingAtHome/fah-issues/issues/1518) to ensure that donors have a much smoother experience if they encounter any issues.

**Comment by PantherX** [comment] 2020-06-05 07:52
@TunaErtemalp 
May I suggest that you post your log files and describe your issues at the Official Forum (https://foldingforum.org/index.php)? It's understandable if you don't have time to debug but there can be others on the Forum who might be willing to replicate your setup in order to replicate your issue(s) which would help out others in the same boat as yours?

**Comment by mattreecebentley** [comment] 2020-06-08 03:39
@TunaErtemalp 
My suspicion is that it occurs when the fahclient is unable to immediately connect to internet on startup - or at least that this is what happens on some machines and not others.

I wouldn't have had a problem posting the log here, but I don't quite have the time to create a new account for a forum and go through all that stuff, just to get some mediocre suggestions. 

This is a bug. I personally don't need help, I'm reporting it because it's a bug, and as a software developer, I APPRECIATE when people tell me what my bugs are.

Even a simple google of "fahcore_a7.exe has stopped working" gives results across wide ranges of time and on many different sites, with no solutions.
https://www.google.co.nz/search?hl=en&q=fahcore_a7.exe+has+stopped+working
Best of luck.

**Comment by PantherX** [comment] 2020-06-08 08:05
@mattreecebentley 
If you're fairly confident that starting the client without an internet issue causes your issue to appear, I am willing to re-open this issue and update your post with all the information for the development team to work on :)

**Comment by mattreecebentley** [comment] 2020-06-17 23:43
I'm not confident, that's merely a hypothesis based on the fact that the error has only occurred on the 3 desktop machines I'm running, all of which are running through ethernet connected to wifi access points, which are turned on at the same time as the computers, whereas the two laptops I have which're connected directly to wifi have not shown the same issue.
It could literally be anything.
That being said, here is an attached log from one of the three machines, after crashing with the noted error message. The errors only occur for CPU computing, not GPU computing, as far as I can tell.
[log.txt](https://github.com/FoldingAtHome/fah-issues/files/4795544/log.txt)

**Comment by PantherX** [comment] 2020-08-28 22:23
@mattreecebentley 
The error `ERROR:Guru Meditation` is generally caused by corrupted files. How are you shutting down the systems? If you were to pause folding, wait for a minute or two and then turn off the system, you can avoid that issue from happening when the system next starts up to fold.

I haven't gotten any idea about the second issue 😞
