### ISSUE TITLE
Can't launch Folding@Home Control on M1 MacBook Air

### ISSUE THREAD

**Issue by unbeatable-101** [FoldingAtHome/fah-issues#1611] opened 2020-12-26 19:29 UTC
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.21
* **Operating System**: macOS 11.1
* **Browser**: Firefox 85.0b4

----
## Expected Behavior

The app launches under Rosetta 2

----
## Current Behavior

It doesn't lauch at all

----
## Possible Solution (Optional)

Make it a universal binary application or provide a separate arm64 version.

----
## Steps To Reproduce

1. Try to open.
2.
3.

----
## Context

I haven't been able to use the more advanced control.

----

**Comment by unbeatable-101** [comment] 2020-12-27 05:32
Seems to be the same as #1576, but it is still happening

**Comment by kbernhagen** [comment] 2020-12-27 08:14
Yes. This is a duplicate of https://github.com/FoldingAtHome/fah-issues/issues/1576

The issue (broken codesign) is fixed for the next release.

**Closed** 2020-12-27 08:32 UTC
