### ISSUE TITLE
Can't connect to client after time synchronization

### ISSUE THREAD

**Issue by benji2602** [FoldingAtHome/fah-issues#1447] opened 2020-05-02 00:30 UTC
My windows time was off, so I manually synced with the time server, and now the client won't connect to either the FAHControl (stuck on updating) or Web Control (page loads, but no info shows up). FahCore_a7 and FahCore_22 are still running in the background, but I can't tell them to do anything.

Edit: Killing the client and restarting fixed the issue and no progress was lost on the WUs.

**Comment by benji2602** [comment] 2020-05-02 00:44
Looking through the latest log shows these errors:
```
19:52:27:WARNING:WU01:FS00:FahCore crashed with Windows unhandled exception code 0x40010004, searching for this code online may provide more information
19:52:27:WARNING:WU01:FS00:FahCore returned: UNKNOWN_ENUM (1073807364 = 0x40010004)
19:52:27:WU00:FS00:Starting
19:52:27:WU00:FS00:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" C:\Users\bcspe\AppData\Roaming\FAHClient\cores/cores.foldingathome.org/v7/win/64bit/avx/Core_a7.fah/FahCore_a7.exe -dir 00 -suffix 01 -version 706 -lifeline 6824 -checkpoint 15 -np 12
19:52:27:WU00:FS00:Started FahCore on PID 13984
19:52:27:WU00:FS00:FahCore 0xa7 started
19:52:28:WARNING:WU00:FS00:FahCore returned an unknown error code which probably indicates that it crashed
19:52:28:WARNING:WU00:FS00:FahCore returned: UNKNOWN_ENUM (-1073741205 = 0xc000026b)
19:52:28:WU01:FS00:Starting
19:52:28:WU01:FS00:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" C:\Users\bcspe\AppData\Roaming\FAHClient\cores/cores.foldingathome.org/v7/win/64bit/avx/Core_a7.fah/FahCore_a7.exe -dir 01 -suffix 01 -version 706 -lifeline 6824 -checkpoint 15 -np 12
19:52:28:WU01:FS00:Started FahCore on PID 2416
19:52:28:WU01:FS00:FahCore 0xa7 started
19:52:28:WARNING:WU01:FS00:FahCore returned an unknown error code which probably indicates that it crashed
19:52:28:WARNING:WU01:FS00:FahCore returned: UNKNOWN_ENUM (-1073741205 = 0xc000026b)
```
My computer had initially thought it was the next day, so the time that the log has is incorrect. Maybe the difference in what time they thought they were at messed up communication.

**Comment by shorttack** [comment] 2020-05-02 17:25
Try a reboot. If that doesn't work try the diagnostic team at foldingathome.org. Search the board for "UNKNOWN_ENUM (1073807364 = 0x40010004".

Please note that we tend to use GitHub for development issues that are reproducible. For troubleshooting, heading over to the Official Forum is the best option: https://foldingforum.org/index.php where there are lots of Donors who are happy to help out :)
Since this isn't an issue, I will close this now.

**Closed by shorttack** 2020-05-02 17:25 UTC
