### ISSUE TITLE
Huge GPU WU with impossibly tight deadline

### ISSUE THREAD

**Issue by MaartenBaert** [FoldingAtHome/fah-issues#1426] opened 2020-04-25 11:32 UTC
I just got assigned a huge GPU work unit with a deadline that is impossible to meet on the hardware it's running on:

![fah-deadline](https://user-images.githubusercontent.com/829608/80278670-93ecc300-86f8-11ea-9409-09def7ffa642.png)

The deadline is in 1.61 days but it takes 1.95 days to complete when running continuously (this is an older GPU obviously). Normally I get at least 5 days for WUs that take less than a day to complete. Is there a bug in the deadline calculation? If it isn't then this type of WU should only be assigned to more powerful GPUs.

**Comment by PantherX** [comment] 2020-04-25 18:39
Hiya @MaartenBaert,
Please note that we tend to use GitHub for documenting reproducible errors in the clients which allows the developers to fix them. In your case, it seems to be Project issue so can you post those details in the Official Forum: https://foldingforum.org/index.php where the researchers can comment and provide feedback.

Since this is not an issue, I will close this now :)

**Closed by PantherX** 2020-04-25 18:39 UTC

**Comment by jchodera** [comment] 2020-04-25 23:26
@MaartenBaert: Thanks for the report! This is a totally new kind of workload for us, and the huge discrepancy in performance is a bit surprising. We now have a lot of data that will help us address these issues in subsequent projects of this type (relative binding free energy calculations for helping prioritize compound synthesis for COVID-19 collaborations).

Please do use the [Folding Forum](https://foldingforum.org/index.php) for project issues in the future!
