### ISSUE TITLE
File descriptors get passed from FAHClient to FAHCore

### ISSUE THREAD

**Issue by Nuitari** [FoldingAtHome/fah-issues#1443] opened 2020-05-01 06:30 UTC
I'm pretty sure that this is unintentional, but multiple file descriptors get passed from FAHClient to the various FAHCore processes. This include the logfile_01.txt of multiple WUs, TCP sockets for FAHControl and FDs that connect to the GPU devices.

Here are some ps / lsof output:
```
16911 pts/9    Sl+    1:34      \_ FAHClient
16920 pts/9    SNl    0:06          \_ /usr/bin/FAHCoreWrapper /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 10 -suffix 01 -version 706 -lifeline 16911 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 0 -gpu 0
16924 pts/9    SNl   21:01          |   \_ /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 10 -suffix 01 -version 706 -lifeline 16920 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 0 -gpu 0
16934 pts/9    SNl    0:06          \_ /usr/bin/FAHCoreWrapper /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 01 -suffix 01 -version 706 -lifeline 16911 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 6 -gpu 6
16938 pts/9    SNl   11:40          |   \_ /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 01 -suffix 01 -version 706 -lifeline 16934 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 6 -gpu 6
16959 pts/9    SNl    0:06          \_ /usr/bin/FAHCoreWrapper /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 11 -suffix 01 -version 706 -lifeline 16911 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 3 -gpu 3
16965 pts/9    SNl   64:02          |   \_ /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 11 -suffix 01 -version 706 -lifeline 16959 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 3 -gpu 3
17294 pts/9    SNl    0:05          \_ /usr/bin/FAHCoreWrapper /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 00 -suffix 01 -version 706 -lifeline 16911 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 2 -gpu 2
17298 pts/9    RNl   55:43          |   \_ /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 00 -suffix 01 -version 706 -lifeline 17294 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 2 -gpu 2
18798 pts/9    SNl    0:00          \_ /usr/bin/FAHCoreWrapper /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_21.fah/FahCore_21 -dir 08 -suffix 01 -version 706 -lifeline 16911 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 4 -gpu 4
18802 pts/9    SNl    7:40          |   \_ /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_21.fah/FahCore_21 -dir 08 -suffix 01 -version 706 -lifeline 18798 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 4 -gpu 4
18828 pts/9    SNl    0:00          \_ /usr/bin/FAHCoreWrapper /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_21.fah/FahCore_21 -dir 03 -suffix 01 -version 706 -lifeline 16911 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 1 -gpu 1
18832 pts/9    SNl    6:58          |   \_ /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_21.fah/FahCore_21 -dir 03 -suffix 01 -version 706 -lifeline 18828 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 1 -gpu 1
18985 pts/9    SNl    0:00          \_ /usr/bin/FAHCoreWrapper /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 07 -suffix 01 -version 706 -lifeline 16911 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 5 -gpu 5
18989 pts/9    SNl    1:22              \_ /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 -dir 07 -suffix 01 -version 706 -lifeline 18985 -checkpoint 15 -gpu-vendor amd -opencl-platform 0 -opencl-device 5 -gpu 5
```

lsof of FAHClient (PID 16911)
```
COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF     NODE NAME
FAHClient 16911 root  cwd    DIR    0,26     4096 20186658 /root/fahclient_saruman (10.0.2.11:/home/miner)
FAHClient 16911 root  rtd    DIR    0,26     4096 17565011 / (10.0.2.11:/home/miner)
FAHClient 16911 root  txt    REG    0,26  8054104 19139468 /usr/bin/FAHClient (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26   101200 18352323 /lib/x86_64-linux-gnu/libresolv-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26    27000 18352319 /lib/x86_64-linux-gnu/libnss_dns-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26    47600 18352327 /lib/x86_64-linux-gnu/libnss_files-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    CHR 226,134              2939 /dev/dri/renderD134
FAHClient 16911 root  mem    CHR 226,133             19414 /dev/dri/renderD133
FAHClient 16911 root  mem    CHR 226,132             19254 /dev/dri/renderD132
FAHClient 16911 root  mem    CHR 226,131              2712 /dev/dri/renderD131
FAHClient 16911 root  mem    CHR 226,130              2697 /dev/dri/renderD130
FAHClient 16911 root  mem    CHR 226,129              2547 /dev/dri/renderD129
FAHClient 16911 root  mem    REG    0,26 35159824 18350100 /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl12cl64.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26 72613376 18350099 /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26    96640 18350091 /lib/x86_64-linux-gnu/libgcc_s.so.1 (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    CHR 226,128             18699 /dev/dri/renderD128
FAHClient 16911 root  mem    REG    0,26    84616 22939042 /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2.4.0 (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26    55656 22939045 /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0 (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26    31712 18352313 /lib/x86_64-linux-gnu/librt-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26    27632 18350096 /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so.1 (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26  1868984 18352330 /lib/x86_64-linux-gnu/libc-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26  1088952 18352333 /lib/x86_64-linux-gnu/libm-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26    14608 18352315 /lib/x86_64-linux-gnu/libdl-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26   138696 18352317 /lib/x86_64-linux-gnu/libpthread-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root  mem    REG    0,26   162632 18352316 /lib/x86_64-linux-gnu/ld-2.23.so (10.0.2.11:/home/miner)
FAHClient 16911 root    0u   CHR   136,9      0t0       12 /dev/pts/9
FAHClient 16911 root    1u   CHR   136,9      0t0       12 /dev/pts/9
FAHClient 16911 root    2u   CHR   136,9      0t0       12 /dev/pts/9
FAHClient 16911 root    3w   REG    0,26    70592 20185100 /root/fahclient_saruman/log.txt (10.0.2.11:/home/miner)
FAHClient 16911 root    4uw  REG    0,26    65536 30277636 /root/fahclient_saruman/work/client.db (10.0.2.11:/home/miner)
FAHClient 16911 root    5u  IPv4   98548      0t0      TCP *:7396 (LISTEN)
FAHClient 16911 root    6u  IPv4   98549      0t0      TCP *:36330 (LISTEN)
FAHClient 16911 root    7u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FAHClient 16911 root    8u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FAHClient 16911 root    9u   CHR   226,6      0t0     2940 /dev/dri/card6
FAHClient 16911 root   10u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FAHClient 16911 root   11u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FAHClient 16911 root   12u   CHR   226,5      0t0    20079 /dev/dri/card5
FAHClient 16911 root   13u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FAHClient 16911 root   14u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FAHClient 16911 root   15u   CHR   226,4      0t0    19255 /dev/dri/card4
FAHClient 16911 root   16u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FAHClient 16911 root   17u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FAHClient 16911 root   18u   CHR   226,3      0t0    19635 /dev/dri/card3
FAHClient 16911 root   19u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FAHClient 16911 root   20u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FAHClient 16911 root   21u   CHR   226,2      0t0    18945 /dev/dri/card2
FAHClient 16911 root   22u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FAHClient 16911 root   23u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FAHClient 16911 root   24u   CHR   226,1      0t0     2548 /dev/dri/card1
FAHClient 16911 root   25u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FAHClient 16911 root   26u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FAHClient 16911 root   27u   CHR   226,0      0t0    18707 /dev/dri/card0
FAHClient 16911 root   28u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FAHClient 16911 root   29u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FAHClient 16911 root   30u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FAHClient 16911 root   31u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FAHClient 16911 root   32u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FAHClient 16911 root   33u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FAHClient 16911 root   34u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FAHClient 16911 root   35u   REG    0,26    33344 44173050 /root/fahclient_saruman/work/client.db-journal (10.0.2.11:/home/miner)
FAHClient 16911 root   37r   REG    0,26     2684 44303665 /root/fahclient_saruman/work/10/logfile_01.txt (10.0.2.11:/home/miner)
FAHClient 16911 root   39r   REG    0,26     2712 44303690 /root/fahclient_saruman/work/01/logfile_01.txt (10.0.2.11:/home/miner)
FAHClient 16911 root   40r   REG    0,26      859 44173344 /root/fahclient_saruman/work/03/logfile_01.txt (10.0.2.11:/home/miner)
FAHClient 16911 root   41r   REG    0,26     1997 44173507 /root/fahclient_saruman/work/07/logfile_01.txt (10.0.2.11:/home/miner)
FAHClient 16911 root   42r   REG    0,26     3091 44303818 /root/fahclient_saruman/work/11/logfile_01.txt (10.0.2.11:/home/miner)
FAHClient 16911 root   43u  IPv4   97239      0t0      TCP 10.0.2.203:36330->gandalf.nuitari.net:50326 (ESTABLISHED)
FAHClient 16911 root   44r   REG    0,26    70592 20185100 /root/fahclient_saruman/log.txt (10.0.2.11:/home/miner)
FAHClient 16911 root   45r   REG    0,26      904 44173332 /root/fahclient_saruman/work/08/logfile_01.txt (10.0.2.11:/home/miner)
FAHClient 16911 root   46r   REG    0,26     3006 44303760 /root/fahclient_saruman/work/00/logfile_01.txt (10.0.2.11:/home/miner)
```

lsof of FAHCoreWrapper
```
COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF     NODE NAME
FAHCoreWr 18985 root  cwd    DIR    0,26     4096 44173350 /root/fahclient_saruman/work (10.0.2.11:/home/miner)
FAHCoreWr 18985 root  rtd    DIR    0,26     4096 17565011 / (10.0.2.11:/home/miner)
FAHCoreWr 18985 root  txt    REG    0,26   847984 19139469 /usr/bin/FAHCoreWrapper (10.0.2.11:/home/miner)
FAHCoreWr 18985 root  mem    REG    0,26  1868984 18352330 /lib/x86_64-linux-gnu/libc-2.23.so (10.0.2.11:/home/miner)
FAHCoreWr 18985 root  mem    REG    0,26  1088952 18352333 /lib/x86_64-linux-gnu/libm-2.23.so (10.0.2.11:/home/miner)
FAHCoreWr 18985 root  mem    REG    0,26    14608 18352315 /lib/x86_64-linux-gnu/libdl-2.23.so (10.0.2.11:/home/miner)
FAHCoreWr 18985 root  mem    REG    0,26   138696 18352317 /lib/x86_64-linux-gnu/libpthread-2.23.so (10.0.2.11:/home/miner)
FAHCoreWr 18985 root  mem    REG    0,26   162632 18352316 /lib/x86_64-linux-gnu/ld-2.23.so (10.0.2.11:/home/miner)
FAHCoreWr 18985 root    0u   CHR   136,9      0t0       12 /dev/pts/9
FAHCoreWr 18985 root    1w  FIFO    0,13      0t0    98197 pipe
FAHCoreWr 18985 root    2w   CHR     1,3      0t0     1049 /dev/null
FAHCoreWr 18985 root    3w   REG    0,26    70887 20185100 /root/fahclient_saruman/log.txt (10.0.2.11:/home/miner)
FAHCoreWr 18985 root    7u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FAHCoreWr 18985 root   10u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FAHCoreWr 18985 root   13u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FAHCoreWr 18985 root   16u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FAHCoreWr 18985 root   19u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FAHCoreWr 18985 root   22u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FAHCoreWr 18985 root   25u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FAHCoreWr 18985 root   28u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FAHCoreWr 18985 root   29u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FAHCoreWr 18985 root   30u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FAHCoreWr 18985 root   31u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FAHCoreWr 18985 root   32u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FAHCoreWr 18985 root   33u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FAHCoreWr 18985 root   34u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FAHCoreWr 18985 root   36r   REG    0,26  2950656 44303709 /root/fahclient_saruman/work/02/.nfs0000000002a4055d000000c0 (10.0.2.11:/home/miner)
FAHCoreWr 18985 root   37r   REG    0,26     2729 44303665 /root/fahclient_saruman/work/10/logfile_01.txt (10.0.2.11:/home/miner)
FAHCoreWr 18985 root   38u  sock     0,9      0t0    99530 protocol: TCP
FAHCoreWr 18985 root   39r   REG    0,26     2712 44303690 /root/fahclient_saruman/work/01/logfile_01.txt (10.0.2.11:/home/miner)
FAHCoreWr 18985 root   40r   REG    0,26      904 44173344 /root/fahclient_saruman/work/03/logfile_01.txt (10.0.2.11:/home/miner)
FAHCoreWr 18985 root   41w   CHR     1,3      0t0     1049 /dev/null
FAHCoreWr 18985 root   42r   REG    0,26     3091 44303818 /root/fahclient_saruman/work/11/logfile_01.txt (10.0.2.11:/home/miner)
FAHCoreWr 18985 root   43u  IPv4   97239      0t0      TCP 10.0.2.203:36330->gandalf.nuitari.net:50326 (ESTABLISHED)
FAHCoreWr 18985 root   44r   REG    0,26    70887 20185100 /root/fahclient_saruman/log.txt (10.0.2.11:/home/miner)
FAHCoreWr 18985 root   45r   REG    0,26      904 44173332 /root/fahclient_saruman/work/08/logfile_01.txt (10.0.2.11:/home/miner)
FAHCoreWr 18985 root   46r   REG    0,26     3006 44303760 /root/fahclient_saruman/work/00/logfile_01.txt (10.0.2.11:/home/miner)
FAHCoreWr 18985 root   47w  FIFO    0,13      0t0    98197 pipe
```
lsof of FAHCore 22
```
root@saruman:~# lsof -p 18989
COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF     NODE NAME
FahCore_2 18989 root  cwd    DIR    0,26     4096 44173505 /root/fahclient_saruman/work/07/01 (10.0.2.11:/home/miner)
FahCore_2 18989 root  rtd    DIR    0,26     4096 17565011 / (10.0.2.11:/home/miner)
FahCore_2 18989 root  txt    REG    0,26  9770984 32639210 /root/fahclient_saruman/cores/cores.foldingathome.org/v7/lin/64bit/Core_22.fah/FahCore_22 (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    CHR 226,133             19414 /dev/dri/renderD133
FahCore_2 18989 root  mem    CHR 226,134              2939 /dev/dri/renderD134
FahCore_2 18989 root  mem    CHR 226,132             19254 /dev/dri/renderD132
FahCore_2 18989 root  mem    CHR 226,131              2712 /dev/dri/renderD131
FahCore_2 18989 root  mem    CHR 226,130              2697 /dev/dri/renderD130
FahCore_2 18989 root  mem    REG    0,26 72613376 18350099 /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    CHR 226,129              2547 /dev/dri/renderD129
FahCore_2 18989 root  mem    REG    0,26 35159824 18350100 /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl12cl64.so (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    CHR 226,128             18699 /dev/dri/renderD128
FahCore_2 18989 root  mem    REG    0,26    84616 22939042 /opt/amdgpu/lib/x86_64-linux-gnu/libdrm.so.2.4.0 (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26    55656 22939045 /opt/amdgpu/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0 (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26  1868984 18352330 /lib/x86_64-linux-gnu/libc-2.23.so (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26    96640 18350091 /lib/x86_64-linux-gnu/libgcc_s.so.1 (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26  1088952 18352333 /lib/x86_64-linux-gnu/libm-2.23.so (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26  1964904 18482534 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28 (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26    31712 18352313 /lib/x86_64-linux-gnu/librt-2.23.so (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26    14608 18352315 /lib/x86_64-linux-gnu/libdl-2.23.so (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26   138696 18352317 /lib/x86_64-linux-gnu/libpthread-2.23.so (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26    27632 18350096 /opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so.1 (10.0.2.11:/home/miner)
FahCore_2 18989 root  mem    REG    0,26   162632 18352316 /lib/x86_64-linux-gnu/ld-2.23.so (10.0.2.11:/home/miner)
FahCore_2 18989 root    0u   CHR   136,9      0t0       12 /dev/pts/9
FahCore_2 18989 root    1w   REG    0,26     4273 44173512 /root/fahclient_saruman/work/07/01/science.log (10.0.2.11:/home/miner)
FahCore_2 18989 root    2w   REG    0,26     4273 44173512 /root/fahclient_saruman/work/07/01/science.log (10.0.2.11:/home/miner)
FahCore_2 18989 root    3w   REG    0,26    70661 20185100 /root/fahclient_saruman/log.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root    4w   CHR     1,3      0t0     1049 /dev/null
FahCore_2 18989 root    5uW  REG    0,26        6 44173506 /root/fahclient_saruman/work/07/wudata_01.lock (10.0.2.11:/home/miner)
FahCore_2 18989 root    6wW  REG    0,26        6 44173506 /root/fahclient_saruman/work/07/wudata_01.lock (10.0.2.11:/home/miner)
FahCore_2 18989 root    7u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FahCore_2 18989 root    8w   REG    0,26     1997 44173507 /root/fahclient_saruman/work/07/logfile_01.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root   10u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FahCore_2 18989 root   12u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FahCore_2 18989 root   13u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FahCore_2 18989 root   14u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FahCore_2 18989 root   15u   CHR   226,6      0t0     2940 /dev/dri/card6
FahCore_2 18989 root   16u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FahCore_2 18989 root   17u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FahCore_2 18989 root   18u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FahCore_2 18989 root   19u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FahCore_2 18989 root   20u   CHR   226,5      0t0    20079 /dev/dri/card5
FahCore_2 18989 root   21u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FahCore_2 18989 root   22u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FahCore_2 18989 root   23u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FahCore_2 18989 root   24u   CHR   226,4      0t0    19255 /dev/dri/card4
FahCore_2 18989 root   25u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FahCore_2 18989 root   26u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FahCore_2 18989 root   27u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FahCore_2 18989 root   28u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FahCore_2 18989 root   29u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FahCore_2 18989 root   30u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FahCore_2 18989 root   31u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FahCore_2 18989 root   32u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FahCore_2 18989 root   33u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FahCore_2 18989 root   34u   CHR 226,134      0t0     2939 /dev/dri/renderD134
FahCore_2 18989 root   35u   CHR   226,3      0t0    19635 /dev/dri/card3
FahCore_2 18989 root   36r   REG    0,26  2950656 44303709 /root/fahclient_saruman/work/02/.nfs0000000002a4055d000000c0 (10.0.2.11:/home/miner)
FahCore_2 18989 root   37r   REG    0,26     2729 44303665 /root/fahclient_saruman/work/10/logfile_01.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root   38u  sock     0,9      0t0    99530 protocol: TCP
FahCore_2 18989 root   39r   REG    0,26     2712 44303690 /root/fahclient_saruman/work/01/logfile_01.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root   40r   REG    0,26      859 44173344 /root/fahclient_saruman/work/03/logfile_01.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root   41w   CHR     1,3      0t0     1049 /dev/null
FahCore_2 18989 root   42r   REG    0,26     3091 44303818 /root/fahclient_saruman/work/11/logfile_01.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root   43u  IPv4   97239      0t0      TCP 10.0.2.203:36330->gandalf.nuitari.net:50326 (ESTABLISHED)
FahCore_2 18989 root   44r   REG    0,26    70661 20185100 /root/fahclient_saruman/log.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root   45r   REG    0,26      904 44173332 /root/fahclient_saruman/work/08/logfile_01.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root   46r   REG    0,26     3006 44303760 /root/fahclient_saruman/work/00/logfile_01.txt (10.0.2.11:/home/miner)
FahCore_2 18989 root   47w  FIFO    0,13      0t0    98197 pipe
FahCore_2 18989 root   48u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FahCore_2 18989 root   49u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FahCore_2 18989 root   50u   CHR   226,2      0t0    18945 /dev/dri/card2
FahCore_2 18989 root   51u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FahCore_2 18989 root   52u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FahCore_2 18989 root   53u   CHR   226,1      0t0     2548 /dev/dri/card1
FahCore_2 18989 root   54u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FahCore_2 18989 root   55u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FahCore_2 18989 root   56u   CHR   226,0      0t0    18707 /dev/dri/card0
FahCore_2 18989 root   57u   CHR 226,128      0t0    18699 /dev/dri/renderD128
FahCore_2 18989 root   58u   CHR 226,129      0t0     2547 /dev/dri/renderD129
FahCore_2 18989 root   59u   CHR 226,130      0t0     2697 /dev/dri/renderD130
FahCore_2 18989 root   60u   CHR 226,131      0t0     2712 /dev/dri/renderD131
FahCore_2 18989 root   61u   CHR 226,132      0t0    19254 /dev/dri/renderD132
FahCore_2 18989 root   62u   CHR 226,133      0t0    19414 /dev/dri/renderD133
FahCore_2 18989 root   63u   CHR 226,134      0t0     2939 /dev/dri/renderD134
```

In particular, note the commonalities between processes for file descriptors below 48.
This could be a great source of heisenbugs.

Missing FD_CLOEXEC ?

**Comment by shorttack** [comment] 2020-05-01 15:43
@Nuitari Exactly what is the problem or bug you are reporting?

Please note that we tend to use GitHub for development issues that are reproducible. For troubleshooting, heading over to the Official Forum is the best option: https://foldingforum.org/index.php where there are lots of Donors who are happy to help out :)
Since this isn't an issue, I will close this now.

**Closed by shorttack** 2020-05-01 15:43 UTC

**Comment by Nuitari** [comment] 2020-05-10 01:51
It is an issue because on space constrained systems files will not actually get deleted until all file descriptors pointing to a file are closed. This means that all WUs that were running when a WU completes have to finish so that the space gets liberated. 

Right now, on the NFS mount, there are 13 WUs waiting to get cleaned up. There are 7 folding slots on that one.

The one with the USB drive (5 folding slots) actually ran out of space for the FAH directory and caused some WUs to be dropped or seen as corrupt by the server. It killed all progress on 4 of the slots.

**Comment by shorttack** [comment] 2020-05-10 15:30
@Nuitari 

> For troubleshooting, heading over to the Official Forum is the best option: https://foldingforum.org/index.php where there are lots of Donors who are happy to help out :)

I recommend that you Pause your client and **reboot** after making sure you have the best network connection possible. Under normal circumstances (like no folding network server backups), there is no way you'll see 7 unsent units. Check your network connection.

Hand off to foldingforum.org ...

**Comment by Nuitari** [comment] 2020-05-10 16:44
@shorttack This clears the symptom, but not the underlying problem. 

**Please take the time to actually read what I wrote. I never complained about units not getting sent. I'm not even sure you took the time to read the initial post.** 

This is how things look because file descriptors remain open in processes that do not need them:
![image](https://user-images.githubusercontent.com/1740437/81505046-bd8e1880-92ba-11ea-9198-63642b18f147.png)

The log file is littered with this:
16:20:58:ERROR:WU03:FS04:Exception: Failed to remove 'work/03/.nfs0000000002a405af000001fd': Device or resource busy

All because the FAHClient is not properly cleaning file descriptors when forking a new process.
