### ISSUE TITLE
Allow greater automation on when application works by allow to specify CRON timer string

### ISSUE THREAD

**Issue by vini-nu** [FoldingAtHome/fah-issues#1724] opened 2024-03-05 15:59 UTC
**If you want to have more people to use FAH, then you should give more respect when people want to give their computing power to you and pay for it, by giving them as much control timing choices as possible.**

I use FAH to basically turn my PC into room heater and I don't like bitcoining. But I want on FAH to have greater control over when it works. Sadly currently the only option are, "are you AFK or not?" and "at what drainage level do you want to go?". What I would like to have more option, like a first-class citizen. For example, maybe I want to run FAH only when solar green energy are available and I'm AFK, etc. Maybe I want to run FAH, when fluctuable electricity prices changes by hour in EU.

Why CRON? E.g. In Linux crontab are used, which allows to specify periodic work. CRON could give wide options for users on when FAH runs. One CRON when FAH should start working and another when it should pause. On top of CRON string you can always make beautiful and easier UX/UI which programically translate back to cron string. But allow user to specify plain CRON string as well.

How CRON string looks like and translates to: https://crontab.guru/ There are CRON programming libraries exists basically on every programming language.

**Comment by jcoffland** [comment] 2024-03-07 11:05
Duplicate of #300.  Note, you can already use cron to control the client.  Just add your own crontab entries.

**Closed by jcoffland** 2024-03-07 11:05 UTC
