### ISSUE TITLE
Idle Slots Do Not Resume While Idle

### ISSUE THREAD

**Issue by zecanard** [FoldingAtHome/fah-issues#1382] opened 2020-04-18 02:37 UTC
Running the Mac client on macOS Catalina 10.15.4. I have one slot with a single core set to run all the time, and 2 more slots with 3 and 12 cores set to run whenever the computer is idle. I also have an SSH server that I use for some home automation.

The Idle slots run perfectly fine, until a trigger hits my SSH server to execute a command. According to my logs, the following happened the instant my Mac received a command via SSH:

```
01:22:25:WU06:FS05:0xa7:Completed 2400000 out of 2500000 steps (96%)
01:23:04:FS05:Shutting core down
01:23:04:WU06:FS05:0xa7:Caught signal SIGINT(2) on PID 87602
01:23:04:WU06:FS05:0xa7:Exiting, please wait. . .
01:23:05:WU06:FS05:0xa7:Folding@home Core Shutdown: INTERRUPTED
01:23:05:WU06:FS05:FahCore returned: INTERRUPTED (102 = 0x66)
```

Almost an hour later, the Idle slots had not resumed (my display is set to power off after 10 minutes, and from my observations, the Idle slots normally kick in 10 minutes after that, so 20 minutes of idle time in total). My computer was locked and unattended with its display in power-saving mode the whole time.

**Comment by PantherX** [comment] 2020-04-18 02:42
Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed?

Please note that since we haven't investigated what the underlying issue is, I am going to close this ticket. Once the issue is identified and reproducible, an issue will be raised here. GitHub is not used for troubleshooting, the Forum is :)

**Closed by PantherX** 2020-04-18 02:42 UTC

**Comment by zecanard** [comment] 2020-04-18 16:22
Thanks for the heads up. I’ve discovered other situations that seem to cause this interruption, so I’m trying to investigate further. I will create a post on the forum once I have more details.
