### ISSUE TITLE
Windows Crash Multiple Times

### ISSUE THREAD

**Issue by sdbarrish** [FoldingAtHome/fah-issues#1487] opened 2020-05-17 14:32 UTC
## Environment

* OS: Windows 64-bit Pro
* FAH version: 7.6.13

## What were you trying to do

I was folding fine on the GPU

## What happened

Windows Blue Screen Crash

## To Reproduce

Random times, but system is unstable when I fold....System is perfectly stable when I DON'T fold.

I have 32GB of DDR4-3200 RAM, Ryzen 3700x CPU, EVGA RTX 2080 Super GPU

My system has more than adequate resources to fold in the background and do office related stuff in the foreground.

Dump File located at:  https://netorgft3443892-my.sharepoint.com/:u:/g/personal/scott_swelltravelagency_com/EXjiLk7PxFhJm-xoTha84YYBFGO4Gerc6N-5hiS8UL9saQ?e=DPOPtA

~41MB zip file

**Comment by shorttack** [comment] 2020-05-17 15:30
@sdbarrish Lots of possibilities. I recommend reinstalling your nVidia driver "clean install". However, the real assistance for your problem is at foldingforum.

Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed? Once the issue is identified and reproducible, an issue will be raised here. GitHub is not used for troubleshooting, the Forum is. 
-Issue Support-

**Comment by PantherX** [comment] 2020-05-18 07:45
Please note that since this is a troubleshooting matter, I will close this as support is provided at the Official Forum :)

**Closed by PantherX** 2020-05-18 07:45 UTC
Labels: FAHClient, Windows, defect
