### ISSUE TITLE
Fahcore_a7.exe stops working

### ISSUE THREAD

**Issue by NL-Xander** [FoldingAtHome/fah-issues#1408] opened 2020-04-20 17:22 UTC
With project 14190 the FahCore_a7 keeps crashing.
[FahCore error.txt](https://github.com/FoldingAtHome/fah-issues/files/4505042/FahCore.error.txt)

What can i do to fix this problem?

**Comment by shorttack** [comment] 2020-04-20 18:35
Can you please post your log file in the Official Forum: https://foldingforum.org/index.php for the issue to be diagnosed? Once the issue is identified and reproducible, an issue will be raised here. GitHub is not used for troubleshooting, the Forum is.

You can also try the latest version in a clean install with [https://foldingathome.org/beta/](url)
_-Issue Support-_

**Comment by PantherX** [comment] 2020-06-07 05:05
Please note that based on the last comment, I will close this issue as I assume that the Forum has resolved your issue :)

**Closed by PantherX** 2020-06-07 05:05 UTC
Labels: 3.Component - GROMACS Core, 4.OS - Windows

**Comment by FR-joel** [comment] 2020-06-11 11:27
Hello,
since yesterday the program Fahcore_a7.exe has stopped working .
 I updated amd software and checked windows 7(sfc/scannow).
today I desinstalled -reinstalled the fah-installer program but no change.
Signature du problème :
  Nom d’événement de problème:	BEX64
  Nom de l’application:	FahCore_a7.exe
  Version de l’application:	0.0.0.0
  Horodatage de l’application:	5db40af1
  Nom du module par défaut:	FahCore_a7.exe
  Version du module par défaut:	0.0.0.0
  Horodateur du module par défaut:	5db40af1
  Décalage de l’exception:	0000000000d6082d
  Code de l’exception:	c0000417
  Données d’exception:	0000000000000000
  Version du système:	6.1.7601.2.1.0.768.3
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	c97c
  Information supplémentaire n° 2:	c97c8b07c213ef2177b3513715c6d5a7
  Information supplémentaire n° 3:	4f14
  Information supplémentaire n° 4:	4f14416988465b4d19c503a0d492061a
thanks you for you answer
