### ISSUE TITLE
Ubuntu Mate 18.04 (libc6, zlib1g)

### ISSUE THREAD

**Issue by ldrahnik** [FoldingAtHome/fah-issues#1472] opened 2020-05-10 15:19 UTC
Hello,

```
sudo dpkg -i --force-depends fahclient_7.6.13_amd64.deb
...
dpkg: fahclient:amd64: dependency problems, but cofiguring anyway as you requested:
  fahclient: amd64 depends on libc6
  fahclient: amd64 depends on zlib1g
...
```

```
sudo apt install libc6
libc6 is already the newest version (2.27-3ubuntu1)
sudo apt install zlib1g
zlib1g is already the newest version (1:1.2.11..dfsg-0ubuntu2]
```

Thank you

Lukas

**Comment by shorttack** [comment] 2020-05-10 15:23
@ldrahnik Please note that we tend to use GitHub for development issues that are reproducible. For troubleshooting, heading over to the Official Forum is the best option: https://foldingforum.org/index.php where there are lots of Donors who are happy to help out :)
Since this isn't an issue, I will close this now.

Try installing the program by double-clicking the downloaded file icon within the Mate GUI. It's designed for a GUI install.

**Closed by shorttack** 2020-05-10 15:23 UTC
