### ISSUE TITLE
Today's Windows Update breaks GPU detection.

### ISSUE THREAD

**Issue by amandablev** [FoldingAtHome/fah-issues#1373] opened 2020-04-15 20:27 UTC
I had client version 7.5.1 installed and all was folding well for a month with CPU and GPU. Today I installed the latest Windows Update. After that reboot the 7.5.1 client was reporting my gpu as xxx. I had never seen this before. I tried removing and readding the slot and it still looked the same. I was not receiving WUs.

I took this opportunity to download the beta version 7.6.7. After uninstalling 7.5.1 and rebooting Windows, I installed 7.6.7. When I launched the client, it wasn't able to detect any GPUs. I stopped folding and went into my Windows update history. I uninstalled today's Windows update and rebooted. After the reboot the update was still listed. I did this 2 more times, but it never disappeared. However, when I opened the FAHControl 7.6.7 this time, I saw under system info that fahclient detected two GPUs. GPU 0 is the onboard Intel[xxx]. GPU 1 is the GeForce RTX 2080 Super.

I manually set the GPU to GPU 1 through FAHControl Configure and slots. Now the 2080 Super is shown as ready. There aren't any WUs for me to test to see if it works though.

Windows Update shows the update that I tried to uninstall as available for me to download. So even though my system shows it is installed and I have the option to uninstall, it seems it is not actually installed. I have paused all Windows Updates until this bug is fixed. I want to continue to fold on GPUs. Many other users could have multiple problems after apply today's updates.

**Comment by jonstacks** [comment] 2020-04-15 20:31
I'm going to close this. Seems to be a duplicate of #1372

**Comment by shorttack** [comment] 2020-04-15 20:32
Closed: duplicates #1372

**Closed** 2020-04-15 20:32 UTC
Labels: FAHClient, Windows, duplicate

**Comment by amandablev** [comment] 2020-04-15 20:33
Yes, you closed 1372 before I could put in more information, and I didn't have the option to open it. =)

**Comment by bb30994** [comment] 2020-04-15 20:46
It's almost a tradition that Windows Update breaks GPU support.  Whenever they install a new driver for NVidia, they fail to (re-)install the OpenCL driver that was included with those device drivers when they're downloaded from nVidia.  Reinstalling from nvidia.com fixes the problem but meanwhile FAHClient has cleaned up any WUs that were being processed.

**Comment by shorttack** [comment] 2020-04-15 20:48
@bb30994 Thanks for the accurate and eloquent answer.

**Comment by amandablev** [comment] 2020-04-15 20:50
As noted in 1372, reinstalling the nvidia drivers 3 different times did not fix this issue. This included reinstalling the drivers after uninstalling 7.5.1 and rebooting. After opening 7.6.7, no GPUs were detected until I took the other steps.

**Comment by bb30994** [comment] 2020-04-15 20:51
I suspect this is also the cause of #1363

**Comment by informatorius** [comment] 2020-04-17 07:00
Would this corona times be a good reason to contact Microsoft about this missing or misconfigured OpenCL on Windows Driver Update? Maybe they are unaware of the issue? Or would be accept to change behavior temporarily?
