### ISSUE TITLE
Folding@home software stopped?

### ISSUE THREAD

**Issue by titilebelge** [FoldingAtHome/fah-issues#1433] opened 2020-04-28 15:01 UTC
![Sans titre](https://user-images.githubusercontent.com/64484477/80503104-b8070900-8971-11ea-8454-df2806e6b3d3.png)

At 99.99%, the attached pop-up appears. No new points, no WU validated...

Can you help me please?
Or, saying it differently, how can I help you, by making it work correctly?

**Comment by PantherX** [comment] 2020-04-28 20:29
Hiya @titilebelge 
Please note that we tend to use GitHub for development issues that are reproducible. For troubleshooting, heading over to the Official Forum is the best option: https://foldingforum.org/index.php where there are lots of Donors who are happy to help out :)

Since this isn't an issue, I will close this now.

**Closed by PantherX** 2020-04-28 20:29 UTC
