### ISSUE TITLE
Systray icon fails to register (and is missing) in beta 7.4.16 client.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1190] opened 2017-04-08 20:15 UTC
```
19:52:46:        Version: 7.4.16
19:52:46:           Date: Jan 6 2017
19:52:46:           Time: 00:25:14
19:52:46:     Repository: Git
19:52:46:       Revision: a9e9e27dc2ee6ff01398c439677bc27f6cb74032
19:52:46:         Branch: master
19:52:46:       Compiler: Visual C++ 2008
19:52:46:        Options: /TP /nologo /EHa /wd4297 /wd4103 /Ox -arch:SSE /MT
19:52:46:       Platform: win32 10
19:52:46:           Bits: 32
19:52:46:           Mode: Release
19:52:46:******************************* System ********************************
19:52:46:            CPU: AMD A8-6500 APU with Radeon(tm) HD Graphics
19:52:46:         CPU ID: AuthenticAMD Family 21 Model 19 Stepping 1
19:52:46:           CPUs: 4
19:52:46:         Memory: 15.95GiB
19:52:46:    Free Memory: 14.27GiB
19:52:46:        Threads: WINDOWS_THREADS
19:52:46:     OS Version: 6.2
19:52:46:    Has Battery: false
19:52:46:     On Battery: false
19:52:46:     UTC Offset: -7
19:52:46:            PID: 5872
19:52:46:            CWD: C:\Users\Gloria\AppData\Roaming\fahclient
19:52:46:             OS: Windows 10 Home
19:52:46:        OS Arch: AMD64
19:52:46:           GPUs: 2
19:52:46:          GPU 0: Bus:2 Slot:0 Func:0 NVIDIA:3 GK107 [GeForce GT 740]
19:52:46:          GPU 1: Bus:1 Slot:0 Func:0 NVIDIA:5 GM206 [GeForce GTX 960]
19:52:46:  CUDA Device 0: Platform:0 Device:0 Bus:1 Slot:0 Compute:5.2 Driver:8.0
19:52:46:  CUDA Device 1: Platform:0 Device:1 Bus:2 Slot:0 Compute:3.0 Driver:8.0
19:52:46:OpenCL Device 0: Platform:0 Device:0 Bus:1 Slot:0 Compute:1.2 Driver:378.66
19:52:46:OpenCL Device 1: Platform:0 Device:1 Bus:2 Slot:0 Compute:1.2 Driver:378.66
19:52:46:  Win32 Service: false
19:52:46:***********************************************************************
19:52:46:<config>
19:52:46:  <!-- Client Control -->
19:52:46:  <disable-sleep-when-active v='false'/>
19:52:46:
19:52:46:  <!-- HTTP Server -->
19:52:46:  <allow v='127.0.0.1,192.168.1.0/24'/>
19:52:46:
19:52:46:  <!-- Network -->
19:52:46:  <proxy v=':8080'/>
19:52:46:  <!-- Work Unit Control -->
19:52:46:  <next-unit-percentage v='100'/>
19:52:46:
19:52:46:  <!-- Folding Slots -->
19:52:46:  <slot id='0' type='CPU'>
19:52:46:    <client-type v='beta'/>
19:52:46:    <cpus v='2'/>
19:52:46:  </slot>
19:52:46:  <slot id='1' type='GPU'>
19:52:46:    <client-type v='beta'/>
19:52:46:    <max-packet-size v='7'/>
19:52:46:  </slot>
19:52:46:  <slot id='2' type='GPU'>
19:52:46:  </slot>
19:52:46:</config>
19:52:46:Trying to access database...
19:52:46:Successfully acquired database lock
19:52:46:Enabled folding slot 00: READY cpu:2
19:52:46:Enabled folding slot 01: READY gpu:0:GK107 [GeForce GT 740]
19:52:47:Enabled folding slot 02: READY gpu:1:GM206 [GeForce GTX 960]
**19:52:47:ERROR:Exception: Failed to register systray icon: Unspecified error**
```
I looked at the WIndows Event log for 12:52:47 and found two entries, both informing me that Windows had an Unspecified error. ... Big Help!

**Comment by jcoffland** [comment] 2017-04-09 23:11
This is one of the problems holding up the beta client release.

**Comment by bb30994** [comment] 2017-04-09 23:17
Is there a way to set a breakpoint when that Exception occurs?  Presumably a dump would give more information that the message does.

**Comment by jcoffland** [comment] 2017-04-09 23:25
I know what the issue is here.  Windows keeps changing the way systray icons are registered.  Basically they are trying to restrict the ways software can take up screen real estate because of Windows programs that abuse this feature.  It's a matter of updating the systray code so that it works correctly on all the different versions of Windows.  I solved some of this problem already but apparently it's not completely resolved.  In short, there's no need for debugging in this case.

**Comment by bb30994** [comment] 2017-04-11 02:44
> ...because of Windows programs that abuse this feature..
and probably because they want to use the same code on small phones as well as large monitors. ;)

**Comment by jcoffland** [comment] 2018-05-09 20:48
Is this still a problem in v7.4.18?  I'm not seeing it.

**Comment by informatorius** [comment] 2018-05-10 08:45
I got this error when mixing different versions of FahControl and FahClient somehow. I can reproduce it with 7.5.0 beta by running FahClient.exe without user data folder path and then additionally start it normally with Windows link. This way I now have 2 FAHClient.exe instances running which use different data folders. (Maybe that is already evil?) Next I quit the first FahClient.exe which removes the tray icon when I mouse hover about it (which looks like some conflict already). The second FahClient.exe is still running. Now I try to start a third FahClient.exe using Windows link which fails because the data folde is already locked but I also get the tray icon error message (although no tray icon is shown anymore). So maybe the isssue is related with a hidden running FahClient.exe without icon. 
`08:32:09:ERROR:Exception: Failed to register systray icon: Es wurde versucht, auf ein Token zuzugreifen, das nicht vorhanden ist.` The error message is partially in german because of my Windows is german and means: "Tried to access a token which is not there" (Code error messages should always be in english because programming languages are english)

But never saw this in normal usage.

**Comment by jcoffland** [comment] 2018-05-11 19:42
Yeah, that scenario is to be expected.  We don't support multiple clients on the same machine.  I'm not surprised that the systray handle got screwed up.  I'm going to close this.  Reopen if the bug is confirmed on the lastest 7.5.0+.

**Closed by jcoffland** 2018-05-11 19:42 UTC
Labels: FAHClient, Windows, defect
