### ISSUE TITLE
WebControl Client stat link not working

### ISSUE THREAD

**Issue by CoolAEW** [FoldingAtHome/fah-issues#1685] opened 2022-04-03 12:29 UTC
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 7.6.21
* **Operating System**: Windows 11 Pro 21H2 Build 22000.556
* **Browser**: Google Chrome 100.0.4896.60

----
## Expected Behavior

Clicking the "See Stats" button on the Client Web Control page should go to my donor stats page (https://stats.foldingathome.org/donor/194051)

----
## Current Behavior

Clicking the "See Stats" button on the Client Web Control tries to go to "https://stats.foldingathome.org/donor/CoolAEW" with my username at the end instead of my donor ID number.

----
## Possible Solution (Optional)

Change the program to use donor ID instead of donor name in the link 
or
make the stats page work with donor ID and donor name

----
## Steps To Reproduce

1. Start folding client
2. Open Web Control
3. Click "See Stats" next to Points earned

----
## Context

I want to easily view my donor stats from the web control.

----

**Comment by jcoffland** [comment] 2022-04-04 18:39
See: https://github.com/FoldingCommunity/fah-stats-front-end/issues/65

**Comment by jcoffland** [comment] 2022-04-04 18:41
This is a duplicate of #1664.

**Closed by jcoffland** 2022-04-04 18:41 UTC
Labels: 1.Type - Duplicate
