### ISSUE TITLE
FAH 7.6.12 Beta "Failed to get assignment from '18.218.241.186:80'" loop

### ISSUE THREAD

**Issue by Andrew0812** [FoldingAtHome/fah-issues#1430] opened 2020-04-27 08:50 UTC
Hi,

I'm using Beta 7.6.12, as I couldn't get the current release to work with my GPU (TU106M [Geforce RTX 2060 Mobile]). It will download a WU, assign it to my GPU and then finish, but it gets stuck in a loop of not finding a new WU. I've attached a text file with the log. Issue starts at around 07:20.

[FAH Advanced Control Log 26.04.2020-27.04.2020.txt](https://github.com/FoldingAtHome/fah-issues/files/4538452/FAH.Advanced.Control.Log.26.04.2020-27.04.2020.txt)

**Comment by PantherX** [comment] 2020-04-27 09:02
Hiya @Andrew0812,

Please note that we prefer to use GitHub for logging issues that are reproducible for the developers to investigate and fix. General troubleshooting is meant to be over at the Official Forum: https://foldingforum.org/index.php

From the log file attached, it doesn't show any issue. It just means that the GPU is waiting to be assigned a WU and since the demand of GPU WU has exceeded that of GPU WU supply, your GPU is currently idle and will eventually be assigned a WU to fold.

If you require further assistance, please hop over to the aforementioned Forum. Since this isn't an issue, I will now close it :)

**Closed by PantherX** 2020-04-27 09:02 UTC
