### ISSUE TITLE
Amended: Passkey received. Should I start a new team, if yes, how?

### ISSUE THREAD

**Issue by OpenNewFolder** [FoldingAtHome/fah-issues#1616] opened 2021-01-14 19:19 UTC
Your issue may already be reported!
Please search on the [issue tracker](./) before creating one.

## Your Environment

* **F@H Software version**: 
* **Operating System**: 
* **Browser**: 

----
## Expected Behavior

----
## Current Behavior

----
## Possible Solution (Optional)

----
## Steps To Reproduce

1.
2.
3.

----
## Context

----

**Comment by jcoffland** [comment] 2021-01-14 21:07
Duplicate of #1420.  Please search the existing issues before filing new ones.  Also, filling out the requested information is not optional.

**Closed by jcoffland** 2021-01-14 21:07 UTC
Labels: 1.Type - Duplicate

**Comment by OpenNewFolder** [comment] 2021-01-14 21:27
Where is search window?

How to start TEAM?
________________________________

**Comment by OpenNewFolder** [comment] 2021-01-15 01:07
https://apps.foldingathome.org/teamstats/team268531.html

started new team, does not seem to be functioning ?

I am a newb so sorry if this is in wrong area.

Thanks in advance.

Mike
________________________________

**Comment by jcoffland** [comment] 2021-01-15 01:12
GitHub search is at the top of the page.  Please ask for help with creating a team at https://foldingforum.org/.

**Comment by OpenNewFolder** [comment] 2021-01-15 04:39
i created a team, it is not functioning....

https://apps.foldingathome.org/teamstats/team268531.html
________________________________

**Comment by PantherX** [comment] 2021-01-15 09:07
@OpenNewFolder please see my comment here: https://github.com/FoldingAtHome/fah-issues/issues/1617#issuecomment-760768280
