### ISSUE TITLE
inconsistent hilighting in inital screen of FAHControl

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-issues#1181] opened 2017-02-07 17:44 UTC
FAHControl 7.4.16 (and earlier).

When selecting a new Client from the left panel, inconsistent information is highlighted.  
![hilight](https://cloud.githubusercontent.com/assets/5483435/22703334/afd8a49e-ed18-11e6-8f9e-e71c9a117f13.PNG)

In this case, Slot 0 is highlighted which corresponds to WU01, not the highlighted WU00.  The hilighted WU0 actually folding in Slot 2.
After selecting either a new Slot or a new WU is selected the proper coherence established and it is maintained after that.

**Comment by jcoffland** [comment] 2017-02-22 22:17
I believe this is a duplicate of #1127.

**Comment by informatorius** [comment] 2018-05-08 14:26
Created a solution https://github.com/FoldingAtHome/fah-control/pull/27

**Comment by jcoffland** [comment] 2018-05-09 22:31
Fixed.

**Closed by jcoffland** 2018-05-09 22:31 UTC
Labels: FAHControl

**Comment by informatorius** [comment] 2018-05-10 13:52
Makes a problem in 7.5.0 beta: Now it is selecting the slot's corresponding queue item always on each ui update. But if user selected a different queue item then it should stay on that queue item. 

The additional select call in code must only be called initially when the selected slot changed - not always on update ui.

**Comment by jcoffland** [comment] 2018-05-11 19:47
Fix will be in 7.5.1.
